stages:
  - test
  - build
  - deploy
  - chatops

# workflow:
#   rules:
#     - if: $CI_MERGE_REQUEST_IID
#     - if: $CI_COMMIT_TAG
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


ui-test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.28.1-focal
  variables:
    COHERE_API_KEY: $COHERE_API_KEY
  script:
   - npm install
   - npx playwright test --grep-invert '@slow'
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
      - results.xml
    reports:
      junit: results.xml
  rules:
      - when: manual


pages:
  stage: deploy
  image: node:lts
  script:
    - npm install
    - npm run build
    - cp -r dist/* public
    - echo "Updated pages with $CI_COMMIT_REF_NAME"
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  environment:
    name: production
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == "ci-cd"
    - if: $CI_PIPELINE_SOURCE == "chat"
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: manual

hello:
  stage: chatops
  rules:
    - if: $CI_PIPELINE_SOURCE == "chat"
  script:
    - echo "Hello World"